### ISSUE TITLE
TypeError: Cannot read property 'definitions' of undefined

### ISSUE THREAD

**Issue by paales** [n1ru4l/graphql-codegen-relay-plugins#151]
Cool plugin! Actually required for the project as the backend is having some trouble with handling fragments properly..

Running into:

```
    TypeError: Cannot read property 'definitions' of undefined
        at /Users/paulhachmang/Sites/reachdigital-next/node_modules/@n1ru4l/graphql-codegen-relay-optimizer-plugin/dist/main/index.js:33:47
        at Array.reduce (<anonymous>)
        at Object.exports.plugin (/Users/paulhachmang/Sites/reachdigital-next/node_modules/@n1ru4l/graphql-codegen-relay-optimizer-plugin/dist/main/index.js:32:34)
        at executePlugin (/Users/paulhachmang/Sites/reachdigital-next/dist/graphql-codegen-core/src/execute-plugin.js:29:35)
        at /Users/paulhachmang/Sites/reachdigital-next/dist/graphql-codegen-core/src/codegen.js:77:30
        at Array.map (<anonymous>)
        at Object.codegen (/Users/paulhachmang/Sites/reachdigital-next/dist/graphql-codegen-core/src/codegen.js:67:54)
        at process (/Users/paulhachmang/Sites/reachdigital-next/node_modules/@graphql-codegen/cli/bin.js:829:56)
        at async Promise.all (index 0)
        at /Users/paulhachmang/Sites/reachdigital-next/node_modules/@graphql-codegen/cli/bin.js:836:37
        at Task.task (/Users/paulhachmang/Sites/reachdigital-next/node_modules/@graphql-codegen/cli/bin.js:618:17)
```

I did saw this comment:

```
// @TODO way for users to define directives they use, otherwise relay will throw an unknown directive error
// Maybe we can scan the queries and add them dynamically without users having to do some extra stuff
// transformASTSchema creates a new schema instance instead of mutating the old one
```

So I don't have any custom directives in my my queries. There are however graphql files in my node_modules folder that do include them, but I'm not including them in my codegen config. Is it maybe picking up graphql files from there as well?

Codegen file

```yml
overwrite: true
require:
  - ts-node/register/transpile-only
  - tsconfig-paths/register
  - dotenv/config
schema: ./node/meshSchema.ts
documents:
  - '**/*.graphql'
  - '!generated/*.graphql'
  - '!node_modules/**'
generates:
  generated/fragments.json:
    plugins:
      - fragment-matcher
    hooks:
      afterOneFileWrite:
        - prettier --write
  generated/schema.graphql:
    plugins:
      - schema-ast
    config:
      includeDirectives: true
      commentDescriptions: true
    hooks:
      afterOneFileWrite:
        - prettier --write
  generated/graphql.d.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      typesPrefix: GQL
      immutableTypes: false
      noExport: true
      enumsAsTypes: true
      skipTypename: true
      avoidOptionals:
        field: true
        inputValue: false
        object: true
      maybeValue: 'T'
    hooks:
      afterOneFileWrite:
        - prettier --write
  generated/apollo.ts:
    plugins:
      - '@n1ru4l/graphql-codegen-relay-optimizer-plugin'
      - typescript-react-apollo
    config:
      typesPrefix: GQL
      withHOC: false
      withHooks: true
      withComponent: false
    hooks:
      afterOneFileWrite:
        - eslint --fix
        - prettier --write
```
