### ISSUE TITLE
deprecate package once graphql-codegen support is fixed

### ISSUE THREAD

**Issue by n1ru4l** [n1ru4l/graphql-codegen-relay-plugins#184]
Once `flattenGeneratedTypes` is fixed and does inline operations this package can be deprecated and a link to graphql-codegen can be added.

I already tried re-searching some time ago why inlining fragments are broken on graphql-codegen, but due to complexity (package layering) and limited time I had to stop it.

Yesterday I tried upgrading and checked again, but graphql-codegen still did not inline fragments for the operations.

**Comment by samlof** [comment]
Seems like `flattenGeneratedTypes` still not fixed? At least I didn't get it to work with newest `@graphql-codegen/cli@2.6.2`, `@graphql-codegen/typescript@2.4.8` and `@graphql-codegen/typescript-operations@2.3.5`. All the fragments are back to being fragments instead of inlined.

Tried running with codegen.yml
```yml
overwrite: true
schema: "http://localhost:3030/query"
documents:
  - "src/**/*.graphql"
  - "src/**/*.tsx"
generates:
  src/generated/introspection.ts:
    plugins:
      - "urql-introspection"

  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-urql"
    config:
      dedupeOperationSuffix: true
      omitOperationSuffix: true
      skipDocumentsValidation: true
      flattenGeneratedTypes: true
      flattenGeneratedTypesIncludeFragments: true

```
